In [1]:
import numpy as np


In [12]:
arr = np.array(
    [
        [2, 4],
        [1, 3],
    ]
)
arr

array([[2, 4],
       [1, 3]])

In [15]:
arr = np.array(
    [
        [2, 4],
        [1, 3],
    ]
)
n = 5
m = 7

def add_padding(arr, n, m):
    res = arr.copy()
    if n > arr.shape[0]:
        diff = n - arr.shape[0]
        res = np.pad(res, ((0, diff),(0,0)), 'constant', constant_values=0)
    if m > arr.shape[1]:
        diff = m - arr.shape[1]
        res = np.pad(res, ((0, 0),(0,diff)), 'constant', constant_values=0)
        
    return res[:n, :m]

add_padding(arr, 5, 4)

array([[2, 4, 0, 0],
       [1, 3, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [16]:
np.where(arr != 0, 1/arr, 0)

array([[0.5       , 0.25      ],
       [1.        , 0.33333333]])