In [2]:
import numpy as np

In [30]:
a = np.array([[-2,-2], 
[-1,0], 
[0,1],
[1,-1],
[2,2]])
np.matmul(a.T, a)/5

array([[2. , 1.4],
       [1.4, 2. ]])

In [8]:
a

array([[-2, -2],
       [-1,  0],
       [ 0,  1],
       [ 1, -1],
       [ 2,  2]])

In [7]:
a.T

array([[-2, -1,  0,  1,  2],
       [-2,  0,  1, -1,  2]])

In [12]:
a2 = np.array([[2,1.4],
              [1.4, 2]])
np.linalg.eig(a2)

(array([3.4, 0.6]),
 array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [16]:
def normalize(v):
    norm = np.linalg.norm(v)
    if norm == 0: 
       return v
    return v / norm

normalize([1.4, -1.4])

array([ 0.70710678, -0.70710678])

In [15]:
np.linalg.norm([1.4, -1.4])

1.979898987322333

In [19]:
np.cov(a.T)

array([[2.5 , 1.75],
       [1.75, 2.5 ]])

In [20]:
a

array([[-2, -2],
       [-1,  0],
       [ 0,  1],
       [ 1, -1],
       [ 2,  2]])

In [31]:
np.cov(a.T)

array([[2.5 , 1.75],
       [1.75, 2.5 ]])

In [33]:
a.T.dot(a)/(a.shape[0]-1)

array([[2.5 , 1.75],
       [1.75, 2.5 ]])

In [36]:
a = np.array([3,5,1])
a_ids = np.argsort(a)[::-1]
a = [a[i] for i in a_ids]

In [37]:
a = [a[i] for i in a_ids]
a

[5, 3, 1]

In [1]:
import zadania_pca
a = [1,2,3]
a[:2]

[1, 2]

In [4]:
import numpy as np
a = np.array([1,2,3])
a[[2,1,0]]

array([3, 2, 1])